// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ssl_gc_referee_message.proto

#ifndef PROTOBUF_INCLUDED_ssl_5fgc_5freferee_5fmessage_2eproto
#define PROTOBUF_INCLUDED_ssl_5fgc_5freferee_5fmessage_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "ssl_gc_game_event.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_ssl_5fgc_5freferee_5fmessage_2eproto 

namespace protobuf_ssl_5fgc_5freferee_5fmessage_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[4];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_ssl_5fgc_5freferee_5fmessage_2eproto
class GameEventProposalGroup;
class GameEventProposalGroupDefaultTypeInternal;
extern GameEventProposalGroupDefaultTypeInternal _GameEventProposalGroup_default_instance_;
class Referee;
class RefereeDefaultTypeInternal;
extern RefereeDefaultTypeInternal _Referee_default_instance_;
class Referee_Point;
class Referee_PointDefaultTypeInternal;
extern Referee_PointDefaultTypeInternal _Referee_Point_default_instance_;
class Referee_TeamInfo;
class Referee_TeamInfoDefaultTypeInternal;
extern Referee_TeamInfoDefaultTypeInternal _Referee_TeamInfo_default_instance_;
namespace google {
namespace protobuf {
template<> ::GameEventProposalGroup* Arena::CreateMaybeMessage<::GameEventProposalGroup>(Arena*);
template<> ::Referee* Arena::CreateMaybeMessage<::Referee>(Arena*);
template<> ::Referee_Point* Arena::CreateMaybeMessage<::Referee_Point>(Arena*);
template<> ::Referee_TeamInfo* Arena::CreateMaybeMessage<::Referee_TeamInfo>(Arena*);
}  // namespace protobuf
}  // namespace google

enum Referee_Stage {
  Referee_Stage_NORMAL_FIRST_HALF_PRE = 0,
  Referee_Stage_NORMAL_FIRST_HALF = 1,
  Referee_Stage_NORMAL_HALF_TIME = 2,
  Referee_Stage_NORMAL_SECOND_HALF_PRE = 3,
  Referee_Stage_NORMAL_SECOND_HALF = 4,
  Referee_Stage_EXTRA_TIME_BREAK = 5,
  Referee_Stage_EXTRA_FIRST_HALF_PRE = 6,
  Referee_Stage_EXTRA_FIRST_HALF = 7,
  Referee_Stage_EXTRA_HALF_TIME = 8,
  Referee_Stage_EXTRA_SECOND_HALF_PRE = 9,
  Referee_Stage_EXTRA_SECOND_HALF = 10,
  Referee_Stage_PENALTY_SHOOTOUT_BREAK = 11,
  Referee_Stage_PENALTY_SHOOTOUT = 12,
  Referee_Stage_POST_GAME = 13
};
bool Referee_Stage_IsValid(int value);
const Referee_Stage Referee_Stage_Stage_MIN = Referee_Stage_NORMAL_FIRST_HALF_PRE;
const Referee_Stage Referee_Stage_Stage_MAX = Referee_Stage_POST_GAME;
const int Referee_Stage_Stage_ARRAYSIZE = Referee_Stage_Stage_MAX + 1;

const ::google::protobuf::EnumDescriptor* Referee_Stage_descriptor();
inline const ::std::string& Referee_Stage_Name(Referee_Stage value) {
  return ::google::protobuf::internal::NameOfEnum(
    Referee_Stage_descriptor(), value);
}
inline bool Referee_Stage_Parse(
    const ::std::string& name, Referee_Stage* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Referee_Stage>(
    Referee_Stage_descriptor(), name, value);
}
enum Referee_Command {
  Referee_Command_HALT = 0,
  Referee_Command_STOP = 1,
  Referee_Command_NORMAL_START = 2,
  Referee_Command_FORCE_START = 3,
  Referee_Command_PREPARE_KICKOFF_YELLOW = 4,
  Referee_Command_PREPARE_KICKOFF_BLUE = 5,
  Referee_Command_PREPARE_PENALTY_YELLOW = 6,
  Referee_Command_PREPARE_PENALTY_BLUE = 7,
  Referee_Command_DIRECT_FREE_YELLOW = 8,
  Referee_Command_DIRECT_FREE_BLUE = 9,
  Referee_Command_INDIRECT_FREE_YELLOW = 10,
  Referee_Command_INDIRECT_FREE_BLUE = 11,
  Referee_Command_TIMEOUT_YELLOW = 12,
  Referee_Command_TIMEOUT_BLUE = 13,
  Referee_Command_GOAL_YELLOW PROTOBUF_DEPRECATED = 14,
  Referee_Command_GOAL_BLUE PROTOBUF_DEPRECATED = 15,
  Referee_Command_BALL_PLACEMENT_YELLOW = 16,
  Referee_Command_BALL_PLACEMENT_BLUE = 17
};
bool Referee_Command_IsValid(int value);
const Referee_Command Referee_Command_Command_MIN = Referee_Command_HALT;
const Referee_Command Referee_Command_Command_MAX = Referee_Command_BALL_PLACEMENT_BLUE;
const int Referee_Command_Command_ARRAYSIZE = Referee_Command_Command_MAX + 1;

const ::google::protobuf::EnumDescriptor* Referee_Command_descriptor();
inline const ::std::string& Referee_Command_Name(Referee_Command value) {
  return ::google::protobuf::internal::NameOfEnum(
    Referee_Command_descriptor(), value);
}
inline bool Referee_Command_Parse(
    const ::std::string& name, Referee_Command* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Referee_Command>(
    Referee_Command_descriptor(), name, value);
}
// ===================================================================

class Referee_TeamInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Referee.TeamInfo) */ {
 public:
  Referee_TeamInfo();
  virtual ~Referee_TeamInfo();

  Referee_TeamInfo(const Referee_TeamInfo& from);

  inline Referee_TeamInfo& operator=(const Referee_TeamInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Referee_TeamInfo(Referee_TeamInfo&& from) noexcept
    : Referee_TeamInfo() {
    *this = ::std::move(from);
  }

  inline Referee_TeamInfo& operator=(Referee_TeamInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Referee_TeamInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Referee_TeamInfo* internal_default_instance() {
    return reinterpret_cast<const Referee_TeamInfo*>(
               &_Referee_TeamInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Referee_TeamInfo* other);
  friend void swap(Referee_TeamInfo& a, Referee_TeamInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Referee_TeamInfo* New() const final {
    return CreateMaybeMessage<Referee_TeamInfo>(NULL);
  }

  Referee_TeamInfo* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Referee_TeamInfo>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Referee_TeamInfo& from);
  void MergeFrom(const Referee_TeamInfo& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Referee_TeamInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint32 yellow_card_times = 4 [packed = true];
  int yellow_card_times_size() const;
  void clear_yellow_card_times();
  static const int kYellowCardTimesFieldNumber = 4;
  ::google::protobuf::uint32 yellow_card_times(int index) const;
  void set_yellow_card_times(int index, ::google::protobuf::uint32 value);
  void add_yellow_card_times(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      yellow_card_times() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_yellow_card_times();

  // required string name = 1;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // required uint32 score = 2;
  bool has_score() const;
  void clear_score();
  static const int kScoreFieldNumber = 2;
  ::google::protobuf::uint32 score() const;
  void set_score(::google::protobuf::uint32 value);

  // required uint32 red_cards = 3;
  bool has_red_cards() const;
  void clear_red_cards();
  static const int kRedCardsFieldNumber = 3;
  ::google::protobuf::uint32 red_cards() const;
  void set_red_cards(::google::protobuf::uint32 value);

  // required uint32 yellow_cards = 5;
  bool has_yellow_cards() const;
  void clear_yellow_cards();
  static const int kYellowCardsFieldNumber = 5;
  ::google::protobuf::uint32 yellow_cards() const;
  void set_yellow_cards(::google::protobuf::uint32 value);

  // required uint32 timeouts = 6;
  bool has_timeouts() const;
  void clear_timeouts();
  static const int kTimeoutsFieldNumber = 6;
  ::google::protobuf::uint32 timeouts() const;
  void set_timeouts(::google::protobuf::uint32 value);

  // required uint32 timeout_time = 7;
  bool has_timeout_time() const;
  void clear_timeout_time();
  static const int kTimeoutTimeFieldNumber = 7;
  ::google::protobuf::uint32 timeout_time() const;
  void set_timeout_time(::google::protobuf::uint32 value);

  // required uint32 goalkeeper = 8;
  bool has_goalkeeper() const;
  void clear_goalkeeper();
  static const int kGoalkeeperFieldNumber = 8;
  ::google::protobuf::uint32 goalkeeper() const;
  void set_goalkeeper(::google::protobuf::uint32 value);

  // optional uint32 foul_counter = 9;
  bool has_foul_counter() const;
  void clear_foul_counter();
  static const int kFoulCounterFieldNumber = 9;
  ::google::protobuf::uint32 foul_counter() const;
  void set_foul_counter(::google::protobuf::uint32 value);

  // optional uint32 ball_placement_failures = 10;
  bool has_ball_placement_failures() const;
  void clear_ball_placement_failures();
  static const int kBallPlacementFailuresFieldNumber = 10;
  ::google::protobuf::uint32 ball_placement_failures() const;
  void set_ball_placement_failures(::google::protobuf::uint32 value);

  // optional uint32 max_allowed_bots = 13;
  bool has_max_allowed_bots() const;
  void clear_max_allowed_bots();
  static const int kMaxAllowedBotsFieldNumber = 13;
  ::google::protobuf::uint32 max_allowed_bots() const;
  void set_max_allowed_bots(::google::protobuf::uint32 value);

  // optional bool can_place_ball = 12;
  bool has_can_place_ball() const;
  void clear_can_place_ball();
  static const int kCanPlaceBallFieldNumber = 12;
  bool can_place_ball() const;
  void set_can_place_ball(bool value);

  // optional bool bot_substitution_intent = 14;
  bool has_bot_substitution_intent() const;
  void clear_bot_substitution_intent();
  static const int kBotSubstitutionIntentFieldNumber = 14;
  bool bot_substitution_intent() const;
  void set_bot_substitution_intent(bool value);

  // optional bool ball_placement_failures_reached = 15;
  bool has_ball_placement_failures_reached() const;
  void clear_ball_placement_failures_reached();
  static const int kBallPlacementFailuresReachedFieldNumber = 15;
  bool ball_placement_failures_reached() const;
  void set_ball_placement_failures_reached(bool value);

  // @@protoc_insertion_point(class_scope:Referee.TeamInfo)
 private:
  void set_has_name();
  void clear_has_name();
  void set_has_score();
  void clear_has_score();
  void set_has_red_cards();
  void clear_has_red_cards();
  void set_has_yellow_cards();
  void clear_has_yellow_cards();
  void set_has_timeouts();
  void clear_has_timeouts();
  void set_has_timeout_time();
  void clear_has_timeout_time();
  void set_has_goalkeeper();
  void clear_has_goalkeeper();
  void set_has_foul_counter();
  void clear_has_foul_counter();
  void set_has_ball_placement_failures();
  void clear_has_ball_placement_failures();
  void set_has_can_place_ball();
  void clear_has_can_place_ball();
  void set_has_max_allowed_bots();
  void clear_has_max_allowed_bots();
  void set_has_bot_substitution_intent();
  void clear_has_bot_substitution_intent();
  void set_has_ball_placement_failures_reached();
  void clear_has_ball_placement_failures_reached();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > yellow_card_times_;
  mutable int _yellow_card_times_cached_byte_size_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::uint32 score_;
  ::google::protobuf::uint32 red_cards_;
  ::google::protobuf::uint32 yellow_cards_;
  ::google::protobuf::uint32 timeouts_;
  ::google::protobuf::uint32 timeout_time_;
  ::google::protobuf::uint32 goalkeeper_;
  ::google::protobuf::uint32 foul_counter_;
  ::google::protobuf::uint32 ball_placement_failures_;
  ::google::protobuf::uint32 max_allowed_bots_;
  bool can_place_ball_;
  bool bot_substitution_intent_;
  bool ball_placement_failures_reached_;
  friend struct ::protobuf_ssl_5fgc_5freferee_5fmessage_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Referee_Point : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Referee.Point) */ {
 public:
  Referee_Point();
  virtual ~Referee_Point();

  Referee_Point(const Referee_Point& from);

  inline Referee_Point& operator=(const Referee_Point& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Referee_Point(Referee_Point&& from) noexcept
    : Referee_Point() {
    *this = ::std::move(from);
  }

  inline Referee_Point& operator=(Referee_Point&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Referee_Point& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Referee_Point* internal_default_instance() {
    return reinterpret_cast<const Referee_Point*>(
               &_Referee_Point_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(Referee_Point* other);
  friend void swap(Referee_Point& a, Referee_Point& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Referee_Point* New() const final {
    return CreateMaybeMessage<Referee_Point>(NULL);
  }

  Referee_Point* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Referee_Point>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Referee_Point& from);
  void MergeFrom(const Referee_Point& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Referee_Point* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required float x = 1;
  bool has_x() const;
  void clear_x();
  static const int kXFieldNumber = 1;
  float x() const;
  void set_x(float value);

  // required float y = 2;
  bool has_y() const;
  void clear_y();
  static const int kYFieldNumber = 2;
  float y() const;
  void set_y(float value);

  // @@protoc_insertion_point(class_scope:Referee.Point)
 private:
  void set_has_x();
  void clear_has_x();
  void set_has_y();
  void clear_has_y();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  float x_;
  float y_;
  friend struct ::protobuf_ssl_5fgc_5freferee_5fmessage_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Referee : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Referee) */ {
 public:
  Referee();
  virtual ~Referee();

  Referee(const Referee& from);

  inline Referee& operator=(const Referee& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Referee(Referee&& from) noexcept
    : Referee() {
    *this = ::std::move(from);
  }

  inline Referee& operator=(Referee&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Referee& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Referee* internal_default_instance() {
    return reinterpret_cast<const Referee*>(
               &_Referee_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(Referee* other);
  friend void swap(Referee& a, Referee& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Referee* New() const final {
    return CreateMaybeMessage<Referee>(NULL);
  }

  Referee* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Referee>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Referee& from);
  void MergeFrom(const Referee& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Referee* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef Referee_TeamInfo TeamInfo;
  typedef Referee_Point Point;

  typedef Referee_Stage Stage;
  static const Stage NORMAL_FIRST_HALF_PRE =
    Referee_Stage_NORMAL_FIRST_HALF_PRE;
  static const Stage NORMAL_FIRST_HALF =
    Referee_Stage_NORMAL_FIRST_HALF;
  static const Stage NORMAL_HALF_TIME =
    Referee_Stage_NORMAL_HALF_TIME;
  static const Stage NORMAL_SECOND_HALF_PRE =
    Referee_Stage_NORMAL_SECOND_HALF_PRE;
  static const Stage NORMAL_SECOND_HALF =
    Referee_Stage_NORMAL_SECOND_HALF;
  static const Stage EXTRA_TIME_BREAK =
    Referee_Stage_EXTRA_TIME_BREAK;
  static const Stage EXTRA_FIRST_HALF_PRE =
    Referee_Stage_EXTRA_FIRST_HALF_PRE;
  static const Stage EXTRA_FIRST_HALF =
    Referee_Stage_EXTRA_FIRST_HALF;
  static const Stage EXTRA_HALF_TIME =
    Referee_Stage_EXTRA_HALF_TIME;
  static const Stage EXTRA_SECOND_HALF_PRE =
    Referee_Stage_EXTRA_SECOND_HALF_PRE;
  static const Stage EXTRA_SECOND_HALF =
    Referee_Stage_EXTRA_SECOND_HALF;
  static const Stage PENALTY_SHOOTOUT_BREAK =
    Referee_Stage_PENALTY_SHOOTOUT_BREAK;
  static const Stage PENALTY_SHOOTOUT =
    Referee_Stage_PENALTY_SHOOTOUT;
  static const Stage POST_GAME =
    Referee_Stage_POST_GAME;
  static inline bool Stage_IsValid(int value) {
    return Referee_Stage_IsValid(value);
  }
  static const Stage Stage_MIN =
    Referee_Stage_Stage_MIN;
  static const Stage Stage_MAX =
    Referee_Stage_Stage_MAX;
  static const int Stage_ARRAYSIZE =
    Referee_Stage_Stage_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Stage_descriptor() {
    return Referee_Stage_descriptor();
  }
  static inline const ::std::string& Stage_Name(Stage value) {
    return Referee_Stage_Name(value);
  }
  static inline bool Stage_Parse(const ::std::string& name,
      Stage* value) {
    return Referee_Stage_Parse(name, value);
  }

  typedef Referee_Command Command;
  static const Command HALT =
    Referee_Command_HALT;
  static const Command STOP =
    Referee_Command_STOP;
  static const Command NORMAL_START =
    Referee_Command_NORMAL_START;
  static const Command FORCE_START =
    Referee_Command_FORCE_START;
  static const Command PREPARE_KICKOFF_YELLOW =
    Referee_Command_PREPARE_KICKOFF_YELLOW;
  static const Command PREPARE_KICKOFF_BLUE =
    Referee_Command_PREPARE_KICKOFF_BLUE;
  static const Command PREPARE_PENALTY_YELLOW =
    Referee_Command_PREPARE_PENALTY_YELLOW;
  static const Command PREPARE_PENALTY_BLUE =
    Referee_Command_PREPARE_PENALTY_BLUE;
  static const Command DIRECT_FREE_YELLOW =
    Referee_Command_DIRECT_FREE_YELLOW;
  static const Command DIRECT_FREE_BLUE =
    Referee_Command_DIRECT_FREE_BLUE;
  static const Command INDIRECT_FREE_YELLOW =
    Referee_Command_INDIRECT_FREE_YELLOW;
  static const Command INDIRECT_FREE_BLUE =
    Referee_Command_INDIRECT_FREE_BLUE;
  static const Command TIMEOUT_YELLOW =
    Referee_Command_TIMEOUT_YELLOW;
  static const Command TIMEOUT_BLUE =
    Referee_Command_TIMEOUT_BLUE;
  GOOGLE_PROTOBUF_DEPRECATED_ATTR static const Command GOAL_YELLOW =
    Referee_Command_GOAL_YELLOW;
  GOOGLE_PROTOBUF_DEPRECATED_ATTR static const Command GOAL_BLUE =
    Referee_Command_GOAL_BLUE;
  static const Command BALL_PLACEMENT_YELLOW =
    Referee_Command_BALL_PLACEMENT_YELLOW;
  static const Command BALL_PLACEMENT_BLUE =
    Referee_Command_BALL_PLACEMENT_BLUE;
  static inline bool Command_IsValid(int value) {
    return Referee_Command_IsValid(value);
  }
  static const Command Command_MIN =
    Referee_Command_Command_MIN;
  static const Command Command_MAX =
    Referee_Command_Command_MAX;
  static const int Command_ARRAYSIZE =
    Referee_Command_Command_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Command_descriptor() {
    return Referee_Command_descriptor();
  }
  static inline const ::std::string& Command_Name(Command value) {
    return Referee_Command_Name(value);
  }
  static inline bool Command_Parse(const ::std::string& name,
      Command* value) {
    return Referee_Command_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // repeated .GameEvent game_events = 16;
  int game_events_size() const;
  void clear_game_events();
  static const int kGameEventsFieldNumber = 16;
  ::GameEvent* mutable_game_events(int index);
  ::google::protobuf::RepeatedPtrField< ::GameEvent >*
      mutable_game_events();
  const ::GameEvent& game_events(int index) const;
  ::GameEvent* add_game_events();
  const ::google::protobuf::RepeatedPtrField< ::GameEvent >&
      game_events() const;

  // repeated .GameEventProposalGroup game_event_proposals = 17;
  int game_event_proposals_size() const;
  void clear_game_event_proposals();
  static const int kGameEventProposalsFieldNumber = 17;
  ::GameEventProposalGroup* mutable_game_event_proposals(int index);
  ::google::protobuf::RepeatedPtrField< ::GameEventProposalGroup >*
      mutable_game_event_proposals();
  const ::GameEventProposalGroup& game_event_proposals(int index) const;
  ::GameEventProposalGroup* add_game_event_proposals();
  const ::google::protobuf::RepeatedPtrField< ::GameEventProposalGroup >&
      game_event_proposals() const;

  // required .Referee.TeamInfo yellow = 7;
  bool has_yellow() const;
  void clear_yellow();
  static const int kYellowFieldNumber = 7;
  private:
  const ::Referee_TeamInfo& _internal_yellow() const;
  public:
  const ::Referee_TeamInfo& yellow() const;
  ::Referee_TeamInfo* release_yellow();
  ::Referee_TeamInfo* mutable_yellow();
  void set_allocated_yellow(::Referee_TeamInfo* yellow);

  // required .Referee.TeamInfo blue = 8;
  bool has_blue() const;
  void clear_blue();
  static const int kBlueFieldNumber = 8;
  private:
  const ::Referee_TeamInfo& _internal_blue() const;
  public:
  const ::Referee_TeamInfo& blue() const;
  ::Referee_TeamInfo* release_blue();
  ::Referee_TeamInfo* mutable_blue();
  void set_allocated_blue(::Referee_TeamInfo* blue);

  // optional .Referee.Point designated_position = 9;
  bool has_designated_position() const;
  void clear_designated_position();
  static const int kDesignatedPositionFieldNumber = 9;
  private:
  const ::Referee_Point& _internal_designated_position() const;
  public:
  const ::Referee_Point& designated_position() const;
  ::Referee_Point* release_designated_position();
  ::Referee_Point* mutable_designated_position();
  void set_allocated_designated_position(::Referee_Point* designated_position);

  // required uint64 packet_timestamp = 1;
  bool has_packet_timestamp() const;
  void clear_packet_timestamp();
  static const int kPacketTimestampFieldNumber = 1;
  ::google::protobuf::uint64 packet_timestamp() const;
  void set_packet_timestamp(::google::protobuf::uint64 value);

  // required .Referee.Stage stage = 2;
  bool has_stage() const;
  void clear_stage();
  static const int kStageFieldNumber = 2;
  ::Referee_Stage stage() const;
  void set_stage(::Referee_Stage value);

  // optional sint32 stage_time_left = 3;
  bool has_stage_time_left() const;
  void clear_stage_time_left();
  static const int kStageTimeLeftFieldNumber = 3;
  ::google::protobuf::int32 stage_time_left() const;
  void set_stage_time_left(::google::protobuf::int32 value);

  // required .Referee.Command command = 4;
  bool has_command() const;
  void clear_command();
  static const int kCommandFieldNumber = 4;
  ::Referee_Command command() const;
  void set_command(::Referee_Command value);

  // required uint32 command_counter = 5;
  bool has_command_counter() const;
  void clear_command_counter();
  static const int kCommandCounterFieldNumber = 5;
  ::google::protobuf::uint32 command_counter() const;
  void set_command_counter(::google::protobuf::uint32 value);

  // required uint64 command_timestamp = 6;
  bool has_command_timestamp() const;
  void clear_command_timestamp();
  static const int kCommandTimestampFieldNumber = 6;
  ::google::protobuf::uint64 command_timestamp() const;
  void set_command_timestamp(::google::protobuf::uint64 value);

  // optional bool blue_team_on_positive_half = 10;
  bool has_blue_team_on_positive_half() const;
  void clear_blue_team_on_positive_half();
  static const int kBlueTeamOnPositiveHalfFieldNumber = 10;
  bool blue_team_on_positive_half() const;
  void set_blue_team_on_positive_half(bool value);

  // optional .Referee.Command next_command = 12;
  bool has_next_command() const;
  void clear_next_command();
  static const int kNextCommandFieldNumber = 12;
  ::Referee_Command next_command() const;
  void set_next_command(::Referee_Command value);

  // optional int32 current_action_time_remaining = 15;
  bool has_current_action_time_remaining() const;
  void clear_current_action_time_remaining();
  static const int kCurrentActionTimeRemainingFieldNumber = 15;
  ::google::protobuf::int32 current_action_time_remaining() const;
  void set_current_action_time_remaining(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Referee)
 private:
  void set_has_packet_timestamp();
  void clear_has_packet_timestamp();
  void set_has_stage();
  void clear_has_stage();
  void set_has_stage_time_left();
  void clear_has_stage_time_left();
  void set_has_command();
  void clear_has_command();
  void set_has_command_counter();
  void clear_has_command_counter();
  void set_has_command_timestamp();
  void clear_has_command_timestamp();
  void set_has_yellow();
  void clear_has_yellow();
  void set_has_blue();
  void clear_has_blue();
  void set_has_designated_position();
  void clear_has_designated_position();
  void set_has_blue_team_on_positive_half();
  void clear_has_blue_team_on_positive_half();
  void set_has_next_command();
  void clear_has_next_command();
  void set_has_current_action_time_remaining();
  void clear_has_current_action_time_remaining();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::GameEvent > game_events_;
  ::google::protobuf::RepeatedPtrField< ::GameEventProposalGroup > game_event_proposals_;
  ::Referee_TeamInfo* yellow_;
  ::Referee_TeamInfo* blue_;
  ::Referee_Point* designated_position_;
  ::google::protobuf::uint64 packet_timestamp_;
  int stage_;
  ::google::protobuf::int32 stage_time_left_;
  int command_;
  ::google::protobuf::uint32 command_counter_;
  ::google::protobuf::uint64 command_timestamp_;
  bool blue_team_on_positive_half_;
  int next_command_;
  ::google::protobuf::int32 current_action_time_remaining_;
  friend struct ::protobuf_ssl_5fgc_5freferee_5fmessage_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GameEventProposalGroup : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:GameEventProposalGroup) */ {
 public:
  GameEventProposalGroup();
  virtual ~GameEventProposalGroup();

  GameEventProposalGroup(const GameEventProposalGroup& from);

  inline GameEventProposalGroup& operator=(const GameEventProposalGroup& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GameEventProposalGroup(GameEventProposalGroup&& from) noexcept
    : GameEventProposalGroup() {
    *this = ::std::move(from);
  }

  inline GameEventProposalGroup& operator=(GameEventProposalGroup&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GameEventProposalGroup& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GameEventProposalGroup* internal_default_instance() {
    return reinterpret_cast<const GameEventProposalGroup*>(
               &_GameEventProposalGroup_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(GameEventProposalGroup* other);
  friend void swap(GameEventProposalGroup& a, GameEventProposalGroup& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GameEventProposalGroup* New() const final {
    return CreateMaybeMessage<GameEventProposalGroup>(NULL);
  }

  GameEventProposalGroup* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GameEventProposalGroup>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GameEventProposalGroup& from);
  void MergeFrom(const GameEventProposalGroup& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GameEventProposalGroup* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .GameEvent game_event = 1;
  int game_event_size() const;
  void clear_game_event();
  static const int kGameEventFieldNumber = 1;
  ::GameEvent* mutable_game_event(int index);
  ::google::protobuf::RepeatedPtrField< ::GameEvent >*
      mutable_game_event();
  const ::GameEvent& game_event(int index) const;
  ::GameEvent* add_game_event();
  const ::google::protobuf::RepeatedPtrField< ::GameEvent >&
      game_event() const;

  // optional bool accepted = 2;
  bool has_accepted() const;
  void clear_accepted();
  static const int kAcceptedFieldNumber = 2;
  bool accepted() const;
  void set_accepted(bool value);

  // @@protoc_insertion_point(class_scope:GameEventProposalGroup)
 private:
  void set_has_accepted();
  void clear_has_accepted();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::GameEvent > game_event_;
  bool accepted_;
  friend struct ::protobuf_ssl_5fgc_5freferee_5fmessage_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Referee_TeamInfo

// required string name = 1;
inline bool Referee_TeamInfo::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Referee_TeamInfo::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Referee_TeamInfo::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Referee_TeamInfo::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& Referee_TeamInfo::name() const {
  // @@protoc_insertion_point(field_get:Referee.TeamInfo.name)
  return name_.GetNoArena();
}
inline void Referee_TeamInfo::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Referee.TeamInfo.name)
}
#if LANG_CXX11
inline void Referee_TeamInfo::set_name(::std::string&& value) {
  set_has_name();
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Referee.TeamInfo.name)
}
#endif
inline void Referee_TeamInfo::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Referee.TeamInfo.name)
}
inline void Referee_TeamInfo::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Referee.TeamInfo.name)
}
inline ::std::string* Referee_TeamInfo::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:Referee.TeamInfo.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Referee_TeamInfo::release_name() {
  // @@protoc_insertion_point(field_release:Referee.TeamInfo.name)
  if (!has_name()) {
    return NULL;
  }
  clear_has_name();
  return name_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Referee_TeamInfo::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:Referee.TeamInfo.name)
}

// required uint32 score = 2;
inline bool Referee_TeamInfo::has_score() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Referee_TeamInfo::set_has_score() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Referee_TeamInfo::clear_has_score() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Referee_TeamInfo::clear_score() {
  score_ = 0u;
  clear_has_score();
}
inline ::google::protobuf::uint32 Referee_TeamInfo::score() const {
  // @@protoc_insertion_point(field_get:Referee.TeamInfo.score)
  return score_;
}
inline void Referee_TeamInfo::set_score(::google::protobuf::uint32 value) {
  set_has_score();
  score_ = value;
  // @@protoc_insertion_point(field_set:Referee.TeamInfo.score)
}

// required uint32 red_cards = 3;
inline bool Referee_TeamInfo::has_red_cards() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Referee_TeamInfo::set_has_red_cards() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Referee_TeamInfo::clear_has_red_cards() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Referee_TeamInfo::clear_red_cards() {
  red_cards_ = 0u;
  clear_has_red_cards();
}
inline ::google::protobuf::uint32 Referee_TeamInfo::red_cards() const {
  // @@protoc_insertion_point(field_get:Referee.TeamInfo.red_cards)
  return red_cards_;
}
inline void Referee_TeamInfo::set_red_cards(::google::protobuf::uint32 value) {
  set_has_red_cards();
  red_cards_ = value;
  // @@protoc_insertion_point(field_set:Referee.TeamInfo.red_cards)
}

// repeated uint32 yellow_card_times = 4 [packed = true];
inline int Referee_TeamInfo::yellow_card_times_size() const {
  return yellow_card_times_.size();
}
inline void Referee_TeamInfo::clear_yellow_card_times() {
  yellow_card_times_.Clear();
}
inline ::google::protobuf::uint32 Referee_TeamInfo::yellow_card_times(int index) const {
  // @@protoc_insertion_point(field_get:Referee.TeamInfo.yellow_card_times)
  return yellow_card_times_.Get(index);
}
inline void Referee_TeamInfo::set_yellow_card_times(int index, ::google::protobuf::uint32 value) {
  yellow_card_times_.Set(index, value);
  // @@protoc_insertion_point(field_set:Referee.TeamInfo.yellow_card_times)
}
inline void Referee_TeamInfo::add_yellow_card_times(::google::protobuf::uint32 value) {
  yellow_card_times_.Add(value);
  // @@protoc_insertion_point(field_add:Referee.TeamInfo.yellow_card_times)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
Referee_TeamInfo::yellow_card_times() const {
  // @@protoc_insertion_point(field_list:Referee.TeamInfo.yellow_card_times)
  return yellow_card_times_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
Referee_TeamInfo::mutable_yellow_card_times() {
  // @@protoc_insertion_point(field_mutable_list:Referee.TeamInfo.yellow_card_times)
  return &yellow_card_times_;
}

// required uint32 yellow_cards = 5;
inline bool Referee_TeamInfo::has_yellow_cards() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Referee_TeamInfo::set_has_yellow_cards() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Referee_TeamInfo::clear_has_yellow_cards() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Referee_TeamInfo::clear_yellow_cards() {
  yellow_cards_ = 0u;
  clear_has_yellow_cards();
}
inline ::google::protobuf::uint32 Referee_TeamInfo::yellow_cards() const {
  // @@protoc_insertion_point(field_get:Referee.TeamInfo.yellow_cards)
  return yellow_cards_;
}
inline void Referee_TeamInfo::set_yellow_cards(::google::protobuf::uint32 value) {
  set_has_yellow_cards();
  yellow_cards_ = value;
  // @@protoc_insertion_point(field_set:Referee.TeamInfo.yellow_cards)
}

// required uint32 timeouts = 6;
inline bool Referee_TeamInfo::has_timeouts() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Referee_TeamInfo::set_has_timeouts() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Referee_TeamInfo::clear_has_timeouts() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Referee_TeamInfo::clear_timeouts() {
  timeouts_ = 0u;
  clear_has_timeouts();
}
inline ::google::protobuf::uint32 Referee_TeamInfo::timeouts() const {
  // @@protoc_insertion_point(field_get:Referee.TeamInfo.timeouts)
  return timeouts_;
}
inline void Referee_TeamInfo::set_timeouts(::google::protobuf::uint32 value) {
  set_has_timeouts();
  timeouts_ = value;
  // @@protoc_insertion_point(field_set:Referee.TeamInfo.timeouts)
}

// required uint32 timeout_time = 7;
inline bool Referee_TeamInfo::has_timeout_time() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Referee_TeamInfo::set_has_timeout_time() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Referee_TeamInfo::clear_has_timeout_time() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Referee_TeamInfo::clear_timeout_time() {
  timeout_time_ = 0u;
  clear_has_timeout_time();
}
inline ::google::protobuf::uint32 Referee_TeamInfo::timeout_time() const {
  // @@protoc_insertion_point(field_get:Referee.TeamInfo.timeout_time)
  return timeout_time_;
}
inline void Referee_TeamInfo::set_timeout_time(::google::protobuf::uint32 value) {
  set_has_timeout_time();
  timeout_time_ = value;
  // @@protoc_insertion_point(field_set:Referee.TeamInfo.timeout_time)
}

// required uint32 goalkeeper = 8;
inline bool Referee_TeamInfo::has_goalkeeper() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Referee_TeamInfo::set_has_goalkeeper() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Referee_TeamInfo::clear_has_goalkeeper() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Referee_TeamInfo::clear_goalkeeper() {
  goalkeeper_ = 0u;
  clear_has_goalkeeper();
}
inline ::google::protobuf::uint32 Referee_TeamInfo::goalkeeper() const {
  // @@protoc_insertion_point(field_get:Referee.TeamInfo.goalkeeper)
  return goalkeeper_;
}
inline void Referee_TeamInfo::set_goalkeeper(::google::protobuf::uint32 value) {
  set_has_goalkeeper();
  goalkeeper_ = value;
  // @@protoc_insertion_point(field_set:Referee.TeamInfo.goalkeeper)
}

// optional uint32 foul_counter = 9;
inline bool Referee_TeamInfo::has_foul_counter() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void Referee_TeamInfo::set_has_foul_counter() {
  _has_bits_[0] |= 0x00000080u;
}
inline void Referee_TeamInfo::clear_has_foul_counter() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void Referee_TeamInfo::clear_foul_counter() {
  foul_counter_ = 0u;
  clear_has_foul_counter();
}
inline ::google::protobuf::uint32 Referee_TeamInfo::foul_counter() const {
  // @@protoc_insertion_point(field_get:Referee.TeamInfo.foul_counter)
  return foul_counter_;
}
inline void Referee_TeamInfo::set_foul_counter(::google::protobuf::uint32 value) {
  set_has_foul_counter();
  foul_counter_ = value;
  // @@protoc_insertion_point(field_set:Referee.TeamInfo.foul_counter)
}

// optional uint32 ball_placement_failures = 10;
inline bool Referee_TeamInfo::has_ball_placement_failures() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void Referee_TeamInfo::set_has_ball_placement_failures() {
  _has_bits_[0] |= 0x00000100u;
}
inline void Referee_TeamInfo::clear_has_ball_placement_failures() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void Referee_TeamInfo::clear_ball_placement_failures() {
  ball_placement_failures_ = 0u;
  clear_has_ball_placement_failures();
}
inline ::google::protobuf::uint32 Referee_TeamInfo::ball_placement_failures() const {
  // @@protoc_insertion_point(field_get:Referee.TeamInfo.ball_placement_failures)
  return ball_placement_failures_;
}
inline void Referee_TeamInfo::set_ball_placement_failures(::google::protobuf::uint32 value) {
  set_has_ball_placement_failures();
  ball_placement_failures_ = value;
  // @@protoc_insertion_point(field_set:Referee.TeamInfo.ball_placement_failures)
}

// optional bool can_place_ball = 12;
inline bool Referee_TeamInfo::has_can_place_ball() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void Referee_TeamInfo::set_has_can_place_ball() {
  _has_bits_[0] |= 0x00000400u;
}
inline void Referee_TeamInfo::clear_has_can_place_ball() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void Referee_TeamInfo::clear_can_place_ball() {
  can_place_ball_ = false;
  clear_has_can_place_ball();
}
inline bool Referee_TeamInfo::can_place_ball() const {
  // @@protoc_insertion_point(field_get:Referee.TeamInfo.can_place_ball)
  return can_place_ball_;
}
inline void Referee_TeamInfo::set_can_place_ball(bool value) {
  set_has_can_place_ball();
  can_place_ball_ = value;
  // @@protoc_insertion_point(field_set:Referee.TeamInfo.can_place_ball)
}

// optional uint32 max_allowed_bots = 13;
inline bool Referee_TeamInfo::has_max_allowed_bots() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void Referee_TeamInfo::set_has_max_allowed_bots() {
  _has_bits_[0] |= 0x00000200u;
}
inline void Referee_TeamInfo::clear_has_max_allowed_bots() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void Referee_TeamInfo::clear_max_allowed_bots() {
  max_allowed_bots_ = 0u;
  clear_has_max_allowed_bots();
}
inline ::google::protobuf::uint32 Referee_TeamInfo::max_allowed_bots() const {
  // @@protoc_insertion_point(field_get:Referee.TeamInfo.max_allowed_bots)
  return max_allowed_bots_;
}
inline void Referee_TeamInfo::set_max_allowed_bots(::google::protobuf::uint32 value) {
  set_has_max_allowed_bots();
  max_allowed_bots_ = value;
  // @@protoc_insertion_point(field_set:Referee.TeamInfo.max_allowed_bots)
}

// optional bool bot_substitution_intent = 14;
inline bool Referee_TeamInfo::has_bot_substitution_intent() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void Referee_TeamInfo::set_has_bot_substitution_intent() {
  _has_bits_[0] |= 0x00000800u;
}
inline void Referee_TeamInfo::clear_has_bot_substitution_intent() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void Referee_TeamInfo::clear_bot_substitution_intent() {
  bot_substitution_intent_ = false;
  clear_has_bot_substitution_intent();
}
inline bool Referee_TeamInfo::bot_substitution_intent() const {
  // @@protoc_insertion_point(field_get:Referee.TeamInfo.bot_substitution_intent)
  return bot_substitution_intent_;
}
inline void Referee_TeamInfo::set_bot_substitution_intent(bool value) {
  set_has_bot_substitution_intent();
  bot_substitution_intent_ = value;
  // @@protoc_insertion_point(field_set:Referee.TeamInfo.bot_substitution_intent)
}

// optional bool ball_placement_failures_reached = 15;
inline bool Referee_TeamInfo::has_ball_placement_failures_reached() const {
  return (_has_bits_[0] & 0x00001000u) != 0;
}
inline void Referee_TeamInfo::set_has_ball_placement_failures_reached() {
  _has_bits_[0] |= 0x00001000u;
}
inline void Referee_TeamInfo::clear_has_ball_placement_failures_reached() {
  _has_bits_[0] &= ~0x00001000u;
}
inline void Referee_TeamInfo::clear_ball_placement_failures_reached() {
  ball_placement_failures_reached_ = false;
  clear_has_ball_placement_failures_reached();
}
inline bool Referee_TeamInfo::ball_placement_failures_reached() const {
  // @@protoc_insertion_point(field_get:Referee.TeamInfo.ball_placement_failures_reached)
  return ball_placement_failures_reached_;
}
inline void Referee_TeamInfo::set_ball_placement_failures_reached(bool value) {
  set_has_ball_placement_failures_reached();
  ball_placement_failures_reached_ = value;
  // @@protoc_insertion_point(field_set:Referee.TeamInfo.ball_placement_failures_reached)
}

// -------------------------------------------------------------------

// Referee_Point

// required float x = 1;
inline bool Referee_Point::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Referee_Point::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Referee_Point::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Referee_Point::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline float Referee_Point::x() const {
  // @@protoc_insertion_point(field_get:Referee.Point.x)
  return x_;
}
inline void Referee_Point::set_x(float value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:Referee.Point.x)
}

// required float y = 2;
inline bool Referee_Point::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Referee_Point::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Referee_Point::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Referee_Point::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline float Referee_Point::y() const {
  // @@protoc_insertion_point(field_get:Referee.Point.y)
  return y_;
}
inline void Referee_Point::set_y(float value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:Referee.Point.y)
}

// -------------------------------------------------------------------

// Referee

// required uint64 packet_timestamp = 1;
inline bool Referee::has_packet_timestamp() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Referee::set_has_packet_timestamp() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Referee::clear_has_packet_timestamp() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Referee::clear_packet_timestamp() {
  packet_timestamp_ = GOOGLE_ULONGLONG(0);
  clear_has_packet_timestamp();
}
inline ::google::protobuf::uint64 Referee::packet_timestamp() const {
  // @@protoc_insertion_point(field_get:Referee.packet_timestamp)
  return packet_timestamp_;
}
inline void Referee::set_packet_timestamp(::google::protobuf::uint64 value) {
  set_has_packet_timestamp();
  packet_timestamp_ = value;
  // @@protoc_insertion_point(field_set:Referee.packet_timestamp)
}

// required .Referee.Stage stage = 2;
inline bool Referee::has_stage() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Referee::set_has_stage() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Referee::clear_has_stage() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Referee::clear_stage() {
  stage_ = 0;
  clear_has_stage();
}
inline ::Referee_Stage Referee::stage() const {
  // @@protoc_insertion_point(field_get:Referee.stage)
  return static_cast< ::Referee_Stage >(stage_);
}
inline void Referee::set_stage(::Referee_Stage value) {
  assert(::Referee_Stage_IsValid(value));
  set_has_stage();
  stage_ = value;
  // @@protoc_insertion_point(field_set:Referee.stage)
}

// optional sint32 stage_time_left = 3;
inline bool Referee::has_stage_time_left() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Referee::set_has_stage_time_left() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Referee::clear_has_stage_time_left() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Referee::clear_stage_time_left() {
  stage_time_left_ = 0;
  clear_has_stage_time_left();
}
inline ::google::protobuf::int32 Referee::stage_time_left() const {
  // @@protoc_insertion_point(field_get:Referee.stage_time_left)
  return stage_time_left_;
}
inline void Referee::set_stage_time_left(::google::protobuf::int32 value) {
  set_has_stage_time_left();
  stage_time_left_ = value;
  // @@protoc_insertion_point(field_set:Referee.stage_time_left)
}

// required .Referee.Command command = 4;
inline bool Referee::has_command() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Referee::set_has_command() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Referee::clear_has_command() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Referee::clear_command() {
  command_ = 0;
  clear_has_command();
}
inline ::Referee_Command Referee::command() const {
  // @@protoc_insertion_point(field_get:Referee.command)
  return static_cast< ::Referee_Command >(command_);
}
inline void Referee::set_command(::Referee_Command value) {
  assert(::Referee_Command_IsValid(value));
  set_has_command();
  command_ = value;
  // @@protoc_insertion_point(field_set:Referee.command)
}

// required uint32 command_counter = 5;
inline bool Referee::has_command_counter() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void Referee::set_has_command_counter() {
  _has_bits_[0] |= 0x00000080u;
}
inline void Referee::clear_has_command_counter() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void Referee::clear_command_counter() {
  command_counter_ = 0u;
  clear_has_command_counter();
}
inline ::google::protobuf::uint32 Referee::command_counter() const {
  // @@protoc_insertion_point(field_get:Referee.command_counter)
  return command_counter_;
}
inline void Referee::set_command_counter(::google::protobuf::uint32 value) {
  set_has_command_counter();
  command_counter_ = value;
  // @@protoc_insertion_point(field_set:Referee.command_counter)
}

// required uint64 command_timestamp = 6;
inline bool Referee::has_command_timestamp() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void Referee::set_has_command_timestamp() {
  _has_bits_[0] |= 0x00000100u;
}
inline void Referee::clear_has_command_timestamp() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void Referee::clear_command_timestamp() {
  command_timestamp_ = GOOGLE_ULONGLONG(0);
  clear_has_command_timestamp();
}
inline ::google::protobuf::uint64 Referee::command_timestamp() const {
  // @@protoc_insertion_point(field_get:Referee.command_timestamp)
  return command_timestamp_;
}
inline void Referee::set_command_timestamp(::google::protobuf::uint64 value) {
  set_has_command_timestamp();
  command_timestamp_ = value;
  // @@protoc_insertion_point(field_set:Referee.command_timestamp)
}

// required .Referee.TeamInfo yellow = 7;
inline bool Referee::has_yellow() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Referee::set_has_yellow() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Referee::clear_has_yellow() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Referee::clear_yellow() {
  if (yellow_ != NULL) yellow_->Clear();
  clear_has_yellow();
}
inline const ::Referee_TeamInfo& Referee::_internal_yellow() const {
  return *yellow_;
}
inline const ::Referee_TeamInfo& Referee::yellow() const {
  const ::Referee_TeamInfo* p = yellow_;
  // @@protoc_insertion_point(field_get:Referee.yellow)
  return p != NULL ? *p : *reinterpret_cast<const ::Referee_TeamInfo*>(
      &::_Referee_TeamInfo_default_instance_);
}
inline ::Referee_TeamInfo* Referee::release_yellow() {
  // @@protoc_insertion_point(field_release:Referee.yellow)
  clear_has_yellow();
  ::Referee_TeamInfo* temp = yellow_;
  yellow_ = NULL;
  return temp;
}
inline ::Referee_TeamInfo* Referee::mutable_yellow() {
  set_has_yellow();
  if (yellow_ == NULL) {
    auto* p = CreateMaybeMessage<::Referee_TeamInfo>(GetArenaNoVirtual());
    yellow_ = p;
  }
  // @@protoc_insertion_point(field_mutable:Referee.yellow)
  return yellow_;
}
inline void Referee::set_allocated_yellow(::Referee_TeamInfo* yellow) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete yellow_;
  }
  if (yellow) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      yellow = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, yellow, submessage_arena);
    }
    set_has_yellow();
  } else {
    clear_has_yellow();
  }
  yellow_ = yellow;
  // @@protoc_insertion_point(field_set_allocated:Referee.yellow)
}

// required .Referee.TeamInfo blue = 8;
inline bool Referee::has_blue() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Referee::set_has_blue() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Referee::clear_has_blue() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Referee::clear_blue() {
  if (blue_ != NULL) blue_->Clear();
  clear_has_blue();
}
inline const ::Referee_TeamInfo& Referee::_internal_blue() const {
  return *blue_;
}
inline const ::Referee_TeamInfo& Referee::blue() const {
  const ::Referee_TeamInfo* p = blue_;
  // @@protoc_insertion_point(field_get:Referee.blue)
  return p != NULL ? *p : *reinterpret_cast<const ::Referee_TeamInfo*>(
      &::_Referee_TeamInfo_default_instance_);
}
inline ::Referee_TeamInfo* Referee::release_blue() {
  // @@protoc_insertion_point(field_release:Referee.blue)
  clear_has_blue();
  ::Referee_TeamInfo* temp = blue_;
  blue_ = NULL;
  return temp;
}
inline ::Referee_TeamInfo* Referee::mutable_blue() {
  set_has_blue();
  if (blue_ == NULL) {
    auto* p = CreateMaybeMessage<::Referee_TeamInfo>(GetArenaNoVirtual());
    blue_ = p;
  }
  // @@protoc_insertion_point(field_mutable:Referee.blue)
  return blue_;
}
inline void Referee::set_allocated_blue(::Referee_TeamInfo* blue) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete blue_;
  }
  if (blue) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      blue = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, blue, submessage_arena);
    }
    set_has_blue();
  } else {
    clear_has_blue();
  }
  blue_ = blue;
  // @@protoc_insertion_point(field_set_allocated:Referee.blue)
}

// optional .Referee.Point designated_position = 9;
inline bool Referee::has_designated_position() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Referee::set_has_designated_position() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Referee::clear_has_designated_position() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Referee::clear_designated_position() {
  if (designated_position_ != NULL) designated_position_->Clear();
  clear_has_designated_position();
}
inline const ::Referee_Point& Referee::_internal_designated_position() const {
  return *designated_position_;
}
inline const ::Referee_Point& Referee::designated_position() const {
  const ::Referee_Point* p = designated_position_;
  // @@protoc_insertion_point(field_get:Referee.designated_position)
  return p != NULL ? *p : *reinterpret_cast<const ::Referee_Point*>(
      &::_Referee_Point_default_instance_);
}
inline ::Referee_Point* Referee::release_designated_position() {
  // @@protoc_insertion_point(field_release:Referee.designated_position)
  clear_has_designated_position();
  ::Referee_Point* temp = designated_position_;
  designated_position_ = NULL;
  return temp;
}
inline ::Referee_Point* Referee::mutable_designated_position() {
  set_has_designated_position();
  if (designated_position_ == NULL) {
    auto* p = CreateMaybeMessage<::Referee_Point>(GetArenaNoVirtual());
    designated_position_ = p;
  }
  // @@protoc_insertion_point(field_mutable:Referee.designated_position)
  return designated_position_;
}
inline void Referee::set_allocated_designated_position(::Referee_Point* designated_position) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete designated_position_;
  }
  if (designated_position) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      designated_position = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, designated_position, submessage_arena);
    }
    set_has_designated_position();
  } else {
    clear_has_designated_position();
  }
  designated_position_ = designated_position;
  // @@protoc_insertion_point(field_set_allocated:Referee.designated_position)
}

// optional bool blue_team_on_positive_half = 10;
inline bool Referee::has_blue_team_on_positive_half() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void Referee::set_has_blue_team_on_positive_half() {
  _has_bits_[0] |= 0x00000200u;
}
inline void Referee::clear_has_blue_team_on_positive_half() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void Referee::clear_blue_team_on_positive_half() {
  blue_team_on_positive_half_ = false;
  clear_has_blue_team_on_positive_half();
}
inline bool Referee::blue_team_on_positive_half() const {
  // @@protoc_insertion_point(field_get:Referee.blue_team_on_positive_half)
  return blue_team_on_positive_half_;
}
inline void Referee::set_blue_team_on_positive_half(bool value) {
  set_has_blue_team_on_positive_half();
  blue_team_on_positive_half_ = value;
  // @@protoc_insertion_point(field_set:Referee.blue_team_on_positive_half)
}

// optional .Referee.Command next_command = 12;
inline bool Referee::has_next_command() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void Referee::set_has_next_command() {
  _has_bits_[0] |= 0x00000400u;
}
inline void Referee::clear_has_next_command() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void Referee::clear_next_command() {
  next_command_ = 0;
  clear_has_next_command();
}
inline ::Referee_Command Referee::next_command() const {
  // @@protoc_insertion_point(field_get:Referee.next_command)
  return static_cast< ::Referee_Command >(next_command_);
}
inline void Referee::set_next_command(::Referee_Command value) {
  assert(::Referee_Command_IsValid(value));
  set_has_next_command();
  next_command_ = value;
  // @@protoc_insertion_point(field_set:Referee.next_command)
}

// repeated .GameEvent game_events = 16;
inline int Referee::game_events_size() const {
  return game_events_.size();
}
inline ::GameEvent* Referee::mutable_game_events(int index) {
  // @@protoc_insertion_point(field_mutable:Referee.game_events)
  return game_events_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::GameEvent >*
Referee::mutable_game_events() {
  // @@protoc_insertion_point(field_mutable_list:Referee.game_events)
  return &game_events_;
}
inline const ::GameEvent& Referee::game_events(int index) const {
  // @@protoc_insertion_point(field_get:Referee.game_events)
  return game_events_.Get(index);
}
inline ::GameEvent* Referee::add_game_events() {
  // @@protoc_insertion_point(field_add:Referee.game_events)
  return game_events_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::GameEvent >&
Referee::game_events() const {
  // @@protoc_insertion_point(field_list:Referee.game_events)
  return game_events_;
}

// repeated .GameEventProposalGroup game_event_proposals = 17;
inline int Referee::game_event_proposals_size() const {
  return game_event_proposals_.size();
}
inline void Referee::clear_game_event_proposals() {
  game_event_proposals_.Clear();
}
inline ::GameEventProposalGroup* Referee::mutable_game_event_proposals(int index) {
  // @@protoc_insertion_point(field_mutable:Referee.game_event_proposals)
  return game_event_proposals_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::GameEventProposalGroup >*
Referee::mutable_game_event_proposals() {
  // @@protoc_insertion_point(field_mutable_list:Referee.game_event_proposals)
  return &game_event_proposals_;
}
inline const ::GameEventProposalGroup& Referee::game_event_proposals(int index) const {
  // @@protoc_insertion_point(field_get:Referee.game_event_proposals)
  return game_event_proposals_.Get(index);
}
inline ::GameEventProposalGroup* Referee::add_game_event_proposals() {
  // @@protoc_insertion_point(field_add:Referee.game_event_proposals)
  return game_event_proposals_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::GameEventProposalGroup >&
Referee::game_event_proposals() const {
  // @@protoc_insertion_point(field_list:Referee.game_event_proposals)
  return game_event_proposals_;
}

// optional int32 current_action_time_remaining = 15;
inline bool Referee::has_current_action_time_remaining() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void Referee::set_has_current_action_time_remaining() {
  _has_bits_[0] |= 0x00000800u;
}
inline void Referee::clear_has_current_action_time_remaining() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void Referee::clear_current_action_time_remaining() {
  current_action_time_remaining_ = 0;
  clear_has_current_action_time_remaining();
}
inline ::google::protobuf::int32 Referee::current_action_time_remaining() const {
  // @@protoc_insertion_point(field_get:Referee.current_action_time_remaining)
  return current_action_time_remaining_;
}
inline void Referee::set_current_action_time_remaining(::google::protobuf::int32 value) {
  set_has_current_action_time_remaining();
  current_action_time_remaining_ = value;
  // @@protoc_insertion_point(field_set:Referee.current_action_time_remaining)
}

// -------------------------------------------------------------------

// GameEventProposalGroup

// repeated .GameEvent game_event = 1;
inline int GameEventProposalGroup::game_event_size() const {
  return game_event_.size();
}
inline ::GameEvent* GameEventProposalGroup::mutable_game_event(int index) {
  // @@protoc_insertion_point(field_mutable:GameEventProposalGroup.game_event)
  return game_event_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::GameEvent >*
GameEventProposalGroup::mutable_game_event() {
  // @@protoc_insertion_point(field_mutable_list:GameEventProposalGroup.game_event)
  return &game_event_;
}
inline const ::GameEvent& GameEventProposalGroup::game_event(int index) const {
  // @@protoc_insertion_point(field_get:GameEventProposalGroup.game_event)
  return game_event_.Get(index);
}
inline ::GameEvent* GameEventProposalGroup::add_game_event() {
  // @@protoc_insertion_point(field_add:GameEventProposalGroup.game_event)
  return game_event_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::GameEvent >&
GameEventProposalGroup::game_event() const {
  // @@protoc_insertion_point(field_list:GameEventProposalGroup.game_event)
  return game_event_;
}

// optional bool accepted = 2;
inline bool GameEventProposalGroup::has_accepted() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GameEventProposalGroup::set_has_accepted() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GameEventProposalGroup::clear_has_accepted() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GameEventProposalGroup::clear_accepted() {
  accepted_ = false;
  clear_has_accepted();
}
inline bool GameEventProposalGroup::accepted() const {
  // @@protoc_insertion_point(field_get:GameEventProposalGroup.accepted)
  return accepted_;
}
inline void GameEventProposalGroup::set_accepted(bool value) {
  set_has_accepted();
  accepted_ = value;
  // @@protoc_insertion_point(field_set:GameEventProposalGroup.accepted)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::Referee_Stage> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Referee_Stage>() {
  return ::Referee_Stage_descriptor();
}
template <> struct is_proto_enum< ::Referee_Command> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Referee_Command>() {
  return ::Referee_Command_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_ssl_5fgc_5freferee_5fmessage_2eproto
